pipeline {
    agent any

    stages {

        stage('Check Python') {
            steps {
                bat 'where python'
                bat 'python --version'
            }
        }

        stage('Run QA Tests') {
            steps {
                bat 'python -m unittest AirlineReservation_qa.py'
            }
        }

        stage('Run Application') {
            steps {
                bat 'python AirlineReservation.py'
            }
        }
    }

    post {
        success {
            echo 'Airline Reservation Pipeline PASSED!'
        }

        failure {
            echo 'Airline Reservation Pipeline FAILED!'
        }
    }
}
